const desertBikeImage = "/gallery/ebike-desert-rider.jpg";
const lakeBikeImage = "/gallery/ebike-lake-sunset.jpg";
const lakeRideImage = "/gallery/ebike-lake-ride.jpg";
const motorImage = "/gallery/ebike-motor-repair.jpg";
const forestBikeImage = "/gallery/bike-forest-rider.webp";
const cityBikeImage = "/gallery/bisklet-gallery-01.webp";
const shopImage = "/gallery/dar-bisklette-tekiano.jpg";
const serviceImage = "/gallery/dar-bisklette-kapitalis.jpg";

import catAccessoriesImage from "./assets/cat-accessories.svg";
import featSecureImage from "./assets/feat-secure.svg";
import featLocalImage from "./assets/feat-local.svg";

export const boutiqueProducts = [
  {
    id: "fat-tire-explorer",
    title: "E-Bike Fat Tire Explorer",
    category: "Velo electrique",
    text: "Velo electrique tout chemin avec pneus larges, position confortable et autonomie ideale pour les sorties longues.",
    image: desertBikeImage,
    price: "3 490 DT",
    oldPrice: "3 990 DT",
    discount: "-13%",
    rating: "4.8/5",
    reviews: "34 avis",
    stock: "En stock",
    availability: "En stock",
    priceNumber: 3490,
    useCase: "Aventure",
    badge: "Best seller",
    tags: ["Autonomie 70 km", "Freins disque", "Pneus fat"],
  },
  {
    id: "city-ebike-sunset",
    title: "City E-Bike Sunset",
    category: "Velo urbain",
    text: "Velo urbain electrique pour les trajets quotidiens, les balades au lac et les deplacements sans effort.",
    image: lakeBikeImage,
    price: "2 650 DT",
    oldPrice: "2 950 DT",
    discount: "-10%",
    rating: "4.7/5",
    reviews: "28 avis",
    stock: "Livraison 48h",
    availability: "Livraison 48h",
    priceNumber: 2650,
    useCase: "Ville",
    badge: "Confort",
    tags: ["Ville", "Confort", "Assistance"],
  },
  {
    id: "mountain-bike-sport",
    title: "Mountain Bike Sport",
    category: "VTT",
    text: "VTT robuste pour les circuits, pistes et sorties sportives avec une conduite stable et precise.",
    image: forestBikeImage,
    price: "1 890 DT",
    oldPrice: "2 190 DT",
    discount: "-14%",
    rating: "4.6/5",
    reviews: "41 avis",
    stock: "Disponible",
    availability: "En stock",
    priceNumber: 1890,
    useCase: "Sport",
    badge: "Promo",
    tags: ["Sport", "Suspension", "Performance"],
  },
  {
    id: "kit-moteur-ebike",
    title: "Kit moteur E-Bike",
    category: "Pieces & entretien",
    text: "Controle moteur, diagnostic, protection et pieces utiles pour garder votre velo electrique fiable.",
    image: motorImage,
    price: "690 DT",
    oldPrice: "790 DT",
    discount: "-13%",
    rating: "4.9/5",
    reviews: "19 avis",
    stock: "Stock limite",
    availability: "Stock limite",
    priceNumber: 690,
    useCase: "Entretien",
    badge: "Atelier",
    tags: ["Moteur", "Entretien", "E-Bike"],
  },
  {
    id: "urban-commuter-500",
    title: "Urban Commuter 500",
    category: "Velo urbain",
    text: "Velo leger pour la ville avec position droite, garde-boue et porte-bagage pour les trajets quotidiens.",
    image: cityBikeImage,
    price: "1 250 DT",
    oldPrice: "1 490 DT",
    discount: "-16%",
    rating: "4.6/5",
    reviews: "22 avis",
    stock: "En stock",
    availability: "En stock",
    priceNumber: 1250,
    useCase: "Ville",
    badge: "Nouveau",
    tags: ["Ville", "Leger", "Porte-bagage"],
  },
  {
    id: "trekking-lake-pro",
    title: "Trekking Lake Pro",
    category: "Velo electrique",
    text: "E-bike polyvalent pour route, bord de lac et sorties du weekend avec batterie longue duree.",
    image: lakeRideImage,
    price: "3 150 DT",
    oldPrice: "3 590 DT",
    discount: "-12%",
    rating: "4.8/5",
    reviews: "31 avis",
    stock: "Livraison 48h",
    availability: "Livraison 48h",
    priceNumber: 3150,
    useCase: "Touring",
    badge: "Autonomie",
    tags: ["Touring", "Batterie 65 km", "Confort"],
  },
  {
    id: "casque-urbain-led",
    title: "Casque urbain LED",
    category: "Accessoires",
    text: "Casque ventile avec lumiere arriere integree, parfait pour rouler visible en ville.",
    image: shopImage,
    price: "145 DT",
    oldPrice: "175 DT",
    discount: "-17%",
    rating: "4.7/5",
    reviews: "53 avis",
    stock: "En stock",
    availability: "En stock",
    priceNumber: 145,
    useCase: "Securite",
    badge: "Visible",
    tags: ["LED", "Securite", "Ville"],
  },
  {
    id: "pack-antivol-premium",
    title: "Pack antivol premium",
    category: "Accessoires",
    text: "Antivol U renforce avec cable secondaire et support cadre pour proteger le velo au quotidien.",
    image: serviceImage,
    price: "115 DT",
    oldPrice: "139 DT",
    discount: "-17%",
    rating: "4.9/5",
    reviews: "46 avis",
    stock: "En stock",
    availability: "En stock",
    priceNumber: 115,
    useCase: "Securite",
    badge: "Top avis",
    tags: ["Antivol U", "Cable", "Support"],
  },
  {
    id: "pneu-fat-grip",
    title: "Pneu Fat Grip 20x4",
    category: "Pieces & entretien",
    text: "Pneu large pour e-bike fat tire avec gomme accrocheuse, ideal sable, route et chemin.",
    image: desertBikeImage,
    price: "180 DT",
    oldPrice: "220 DT",
    discount: "-18%",
    rating: "4.5/5",
    reviews: "17 avis",
    stock: "Stock limite",
    availability: "Stock limite",
    priceNumber: 180,
    useCase: "Entretien",
    badge: "Grip",
    tags: ["20x4", "Fat tire", "Adherence"],
  },
  {
    id: "revision-ebike-complete",
    title: "Revision E-Bike complete",
    category: "Pieces & entretien",
    text: "Diagnostic moteur, controle freins, transmission, pneus et serrage complet par l'atelier Bisklet.",
    image: motorImage,
    price: "95 DT",
    oldPrice: "120 DT",
    discount: "-21%",
    rating: "5/5",
    reviews: "12 avis",
    stock: "Sur rendez-vous",
    availability: "Sur rendez-vous",
    priceNumber: 95,
    useCase: "Entretien",
    badge: "Service",
    tags: ["Diagnostic", "Freins", "Transmission"],
  },
];

export const boutiqueFilterGroups = [
  {
    label: "Categorie",
    key: "category",
    options: [
      "Velo electrique",
      "Velo urbain",
      "VTT",
      "Accessoires",
      "Pieces & entretien",
    ],
  },
  {
    label: "Usage",
    key: "useCase",
    options: ["Ville", "Aventure", "Sport", "Touring", "Securite", "Entretien"],
  },
  {
    label: "Disponibilite",
    key: "availability",
    options: ["En stock", "Livraison 48h", "Stock limite", "Sur rendez-vous"],
  },
];

export const boutiqueBudgetOptions = [
  { label: "Tous les prix", value: "all" },
  { label: "Moins de 200 DT", value: "under-200" },
  { label: "200 - 1 000 DT", value: "200-1000" },
  { label: "1 000 - 2 500 DT", value: "1000-2500" },
  { label: "Plus de 2 500 DT", value: "over-2500" },
];

export const boutiqueHighlights = [
  {
    title: "Caracteristiques exceptionnelles",
    text: "Des equipements choisis pour une experience de conduite optimale : autonomie, resistance et securite.",
    image: featSecureImage,
  },
  {
    title: "Facilite d'utilisation",
    text: "Reservation simple, choix rapide et recuperation pratique selon le besoin du client.",
    image: catAccessoriesImage,
  },
  {
    title: "Mobilite urbaine sans effort",
    text: "Evitez les embouteillages, gagnez du temps et explorez votre ville de maniere plus propre.",
    image: featLocalImage,
  },
];

export const buyingGuide = [
  {
    title: "Pour les trajets courts",
    text: "La trottinette electrique est ideale pour gagner du temps en ville et eviter les embouteillages.",
  },
  {
    title: "Pour rouler tous les jours",
    text: "Le city bike convient aux deplacements quotidiens, aux balades simples et aux parcours urbains.",
  },
  {
    title: "Pour les sorties sportives",
    text: "Le mountain bike apporte plus de stabilite, de resistance et de confort pour les circuits.",
  },
  {
    title: "Pour mieux equiper votre velo",
    text: "Les pieces et accessoires ameliorent la securite, l'entretien et l'experience de conduite.",
  },
];
